#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytorch
Version  : 1.0.1
Release  : 8
URL      : https://github.com/pytorch/pytorch/archive/v1.0.1.tar.gz
Source0  : https://github.com/pytorch/pytorch/archive/v1.0.1.tar.gz
Source1  : https://github.com/ARM-software/ComputeLibrary/archive/292227986edb37b01061afcad6df18ba9d6ccbeb.tar.gz
Source2  : https://github.com/Maratyszcza/FP16/archive/34d4bf01bbf7376f2baa71b8fa148b18524d45cf.tar.gz
Source3  : https://github.com/Maratyszcza/FXdiv/archive/b742d1143724d646cd0f914646f1240eacf5bd73.tar.gz
Source4  : https://github.com/Maratyszcza/NNPACK/archive/1e005b0c2777f39972a4ac15bea03e0e315a3d92.tar.gz
Source5  : https://github.com/Maratyszcza/PeachPy/archive/07d8fde8ac45d7705129475c0f94ed8925b93473.tar.gz
Source6  : https://github.com/Maratyszcza/cpuinfo/archive/c342292afb040c868849bc15e96ab894dceba2bc.tar.gz
Source7  : https://github.com/Maratyszcza/psimd/archive/90a938f30ba414ada2f4b00674ee9631d7d85e19.tar.gz
Source8  : https://github.com/Maratyszcza/pthreadpool/archive/13da0b4c21d17f94150713366420baaf1b5a46f4.tar.gz
Source9  : https://github.com/NVIDIA/nccl/archive/3c6e25210bb1b544748937e5db74db0b9679b95e.tar.gz
Source10  : https://github.com/NVlabs/cub/archive/285aeebaa34b0e8a7670867a2e66c1a52d998d6a.tar.gz
Source11  : https://github.com/PeachPy/enum34/archive/4cfedc426c4e2fc52e3f5c2b4297e15ed8d6b8c7.tar.gz
Source12  : https://github.com/Yangqing/ios-cmake/archive/8abaed637d56f1337d6e1d2c4026e25c1eade724.tar.gz
Source13  : https://github.com/benjaminp/six/archive/15e31431af97e5e64b80af0a3f598d382bcdd49a.tar.gz
Source14  : https://github.com/eigenteam/eigen-git-mirror/archive/f59336cee358f92b959de6a0daf07c4ab2318022.tar.gz
Source15  : https://github.com/facebook/zstd/archive/aec56a52fbab207fc639a1937d1e708a282edca8.tar.gz
Source16  : https://github.com/facebookincubator/gloo/archive/cdeb59d5c82e5401445b4c051bb396f6738d4a19.tar.gz
Source17  : https://github.com/google/benchmark/archive/505be96ab23056580a3a2315abba048f4428b04e.tar.gz
Source18  : https://github.com/google/gemmlowp/archive/8416bab644641a5c0a81ecf91a5cda804af0aee1.tar.gz
Source19  : https://github.com/google/googletest/archive/2fe3bd994b3189899d93f1d5a881e725e046fdc2.tar.gz
Source20  : https://github.com/google/protobuf/archive/2761122b810fe8861004ae785cc3ab39f384d342.tar.gz
Source21  : https://github.com/intel/ARM_NEON_2_x86_SSE/archive/97a126f08ce318023be604d03f88bf0820a9464a.tar.gz
Source22  : https://github.com/intel/ideep/archive/dedff8fb8193fe3a1ea893d4bc852f8ea395b6b3.tar.gz
Source23  : https://github.com/onnx/onnx-tensorrt/archive/fa0964e8477fc004ee2f49ee77ffce0bf7f711a9.tar.gz
Source24  : https://github.com/onnx/onnx/archive/42804705bdbf179d1a98394008417e1392013547.tar.gz
Source25  : https://github.com/pybind/pybind11/archive/5c8746ff135abb390bf95944be593e895a586a50.tar.gz
Source26  : https://github.com/pytorch/QNNPACK/archive/ef05e87cef6b8e719989ce875b5e1c9fdb304c05.tar.gz
Source27  : https://github.com/pytorch/fbgemm/archive/0d5a159b944252e70a677236b570f291943e0543.tar.gz
Source28  : https://github.com/shibatch/sleef/archive/6ff7a135a1e31979d1e1844a2e7171dfbd34f54f.tar.gz
Summary  : Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSD-3-Clause-Attribution BSD-3-Clause-Clear BSL-1.0 GPL-2.0 GPL-3.0 LGPL-2.1 MIT MPL-2.0 MPL-2.0-no-copyleft-exception Unlicense
Requires: pytorch-bin = %{version}-%{release}
Requires: pytorch-license = %{version}-%{release}
Requires: pytorch-python = %{version}-%{release}
Requires: pytorch-python3 = %{version}-%{release}
Requires: PyYAML
Requires: Sphinx
Requires: enum34
Requires: matplotlib
Requires: nose
Requires: numpy
Requires: onnx
Requires: opcodes
Requires: setuptools
Requires: six
Requires: typing
BuildRequires : PyYAML
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : buildreq-meson
BuildRequires : buildreq-scons
BuildRequires : eigen
BuildRequires : eigen-dev
BuildRequires : enum34
BuildRequires : llvm
BuildRequires : mkl-dnn-dev
BuildRequires : numactl-dev
BuildRequires : numpy
BuildRequires : onnx
BuildRequires : opcodes
BuildRequires : openblas-dev
BuildRequires : openmpi-dev
BuildRequires : pluggy
BuildRequires : protobuf-dev
BuildRequires : py-python
BuildRequires : pybind11
BuildRequires : pybind11-dev
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
Bench Template Library
****************************************
Introduction :
The aim of this project is to compare the performance
of available numerical libraries. The code is designed
as generic and modular as possible. Thus, adding new
numerical libraries or new numerical tests should
require minimal effort.

%package bin
Summary: bin components for the pytorch package.
Group: Binaries
Requires: pytorch-license = %{version}-%{release}

%description bin
bin components for the pytorch package.


%package dev
Summary: dev components for the pytorch package.
Group: Development
Requires: pytorch-bin = %{version}-%{release}
Provides: pytorch-devel = %{version}-%{release}

%description dev
dev components for the pytorch package.


%package license
Summary: license components for the pytorch package.
Group: Default

%description license
license components for the pytorch package.


%package python
Summary: python components for the pytorch package.
Group: Default
Requires: pytorch-python3 = %{version}-%{release}

%description python
python components for the pytorch package.


%package python3
Summary: python3 components for the pytorch package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytorch package.


%prep
%setup -q -n pytorch-1.0.1
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 1
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 2
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 3
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 4
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 26
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 17
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 6
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 10
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 14
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 27
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 18
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 16
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 19
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 22
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 12
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 9
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 21
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 24
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 23
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 20
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 7
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 8
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 25
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 11
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 5
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 13
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 28
cd ..
%setup -q -T -D -n pytorch-1.0.1 -b 15
mkdir -p third_party/ComputeLibrary
cp -r %{_topdir}/BUILD/ComputeLibrary-292227986edb37b01061afcad6df18ba9d6ccbeb/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/ComputeLibrary
mkdir -p third_party/FP16
cp -r %{_topdir}/BUILD/FP16-34d4bf01bbf7376f2baa71b8fa148b18524d45cf/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/FP16
mkdir -p third_party/FXdiv
cp -r %{_topdir}/BUILD/FXdiv-b742d1143724d646cd0f914646f1240eacf5bd73/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/FXdiv
mkdir -p third_party/NNPACK
cp -r %{_topdir}/BUILD/NNPACK-1e005b0c2777f39972a4ac15bea03e0e315a3d92/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/NNPACK
mkdir -p third_party/QNNPACK
cp -r %{_topdir}/BUILD/QNNPACK-ef05e87cef6b8e719989ce875b5e1c9fdb304c05/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/QNNPACK
mkdir -p third_party/benchmark
cp -r %{_topdir}/BUILD/benchmark-505be96ab23056580a3a2315abba048f4428b04e/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/benchmark
mkdir -p third_party/cpuinfo
cp -r %{_topdir}/BUILD/cpuinfo-c342292afb040c868849bc15e96ab894dceba2bc/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/cpuinfo
mkdir -p third_party/cub
cp -r %{_topdir}/BUILD/cub-285aeebaa34b0e8a7670867a2e66c1a52d998d6a/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/cub
mkdir -p third_party/eigen
cp -r %{_topdir}/BUILD/eigen-git-mirror-f59336cee358f92b959de6a0daf07c4ab2318022/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/eigen
mkdir -p third_party/fbgemm
cp -r %{_topdir}/BUILD/FBGEMM-0d5a159b944252e70a677236b570f291943e0543/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/fbgemm
mkdir -p third_party/gemmlowp/gemmlowp
cp -r %{_topdir}/BUILD/gemmlowp-8416bab644641a5c0a81ecf91a5cda804af0aee1/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/gemmlowp/gemmlowp
mkdir -p third_party/gloo
cp -r %{_topdir}/BUILD/gloo-cdeb59d5c82e5401445b4c051bb396f6738d4a19/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/gloo
mkdir -p third_party/googletest
cp -r %{_topdir}/BUILD/googletest-2fe3bd994b3189899d93f1d5a881e725e046fdc2/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/googletest
mkdir -p third_party/ideep
cp -r %{_topdir}/BUILD/ideep-dedff8fb8193fe3a1ea893d4bc852f8ea395b6b3/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/ideep
mkdir -p third_party/ios-cmake
cp -r %{_topdir}/BUILD/ios-cmake-8abaed637d56f1337d6e1d2c4026e25c1eade724/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/ios-cmake
mkdir -p third_party/nccl/nccl
cp -r %{_topdir}/BUILD/nccl-3c6e25210bb1b544748937e5db74db0b9679b95e/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/nccl/nccl
mkdir -p third_party/neon2sse
cp -r %{_topdir}/BUILD/ARM_NEON_2_x86_SSE-97a126f08ce318023be604d03f88bf0820a9464a/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/neon2sse
mkdir -p third_party/onnx
cp -r %{_topdir}/BUILD/onnx-42804705bdbf179d1a98394008417e1392013547/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/onnx
mkdir -p third_party/onnx-tensorrt
cp -r %{_topdir}/BUILD/onnx-tensorrt-fa0964e8477fc004ee2f49ee77ffce0bf7f711a9/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/onnx-tensorrt
mkdir -p third_party/protobuf
cp -r %{_topdir}/BUILD/protobuf-2761122b810fe8861004ae785cc3ab39f384d342/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/protobuf
mkdir -p third_party/psimd
cp -r %{_topdir}/BUILD/psimd-90a938f30ba414ada2f4b00674ee9631d7d85e19/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/psimd
mkdir -p third_party/pthreadpool
cp -r %{_topdir}/BUILD/pthreadpool-13da0b4c21d17f94150713366420baaf1b5a46f4/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/pthreadpool
mkdir -p third_party/pybind11
cp -r %{_topdir}/BUILD/pybind11-5c8746ff135abb390bf95944be593e895a586a50/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/pybind11
mkdir -p third_party/python-enum
cp -r %{_topdir}/BUILD/enum34-4cfedc426c4e2fc52e3f5c2b4297e15ed8d6b8c7/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/python-enum
mkdir -p third_party/python-peachpy
cp -r %{_topdir}/BUILD/PeachPy-07d8fde8ac45d7705129475c0f94ed8925b93473/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/python-peachpy
mkdir -p third_party/python-six
cp -r %{_topdir}/BUILD/six-15e31431af97e5e64b80af0a3f598d382bcdd49a/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/python-six
mkdir -p third_party/sleef
cp -r %{_topdir}/BUILD/sleef-6ff7a135a1e31979d1e1844a2e7171dfbd34f54f/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/sleef
mkdir -p third_party/zstd
cp -r %{_topdir}/BUILD/zstd-aec56a52fbab207fc639a1937d1e708a282edca8/* %{_topdir}/BUILD/pytorch-1.0.1/third_party/zstd

%build
## build_prepend content
export NO_CUDA=1
export USE_OPENMP=ON
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549393698
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
## install_prepend content
export NO_CUDA=1
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/pytorch
cp LICENSE %{buildroot}/usr/share/package-licenses/pytorch/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/pytorch/NOTICE
cp caffe2/contrib/cuda-convnet2/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/caffe2_contrib_cuda-convnet2_LICENSE
cp caffe2/mobile/contrib/libopencl-stub/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/caffe2_mobile_contrib_libopencl-stub_LICENSE
cp third_party/ComputeLibrary/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_LICENSE
cp third_party/ComputeLibrary/include/half/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_include_half_LICENSE.txt
cp third_party/FP16/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_FP16_LICENSE
cp third_party/FXdiv/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_FXdiv_LICENSE
cp third_party/NNPACK/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_NNPACK_LICENSE
cp third_party/QNNPACK/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_QNNPACK_LICENSE
cp third_party/QNNPACK/deps/clog/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_QNNPACK_deps_clog_LICENSE
cp third_party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_benchmark_LICENSE
cp third_party/cpuinfo/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_cpuinfo_LICENSE
cp third_party/cpuinfo/deps/clog/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_cpuinfo_deps_clog_LICENSE
cp third_party/cub/LICENSE.TXT %{buildroot}/usr/share/package-licenses/pytorch/third_party_cub_LICENSE.TXT
cp third_party/eigen/COPYING.BSD %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.BSD
cp third_party/eigen/COPYING.GPL %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.GPL
cp third_party/eigen/COPYING.LGPL %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.LGPL
cp third_party/eigen/COPYING.MINPACK %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MINPACK
cp third_party/eigen/COPYING.MPL2 %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MPL2
cp third_party/eigen/COPYING.README %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.README
cp third_party/eigen/bench/btl/COPYING %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_bench_btl_COPYING
cp third_party/fbgemm/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_fbgemm_LICENSE
cp third_party/gemmlowp/gemmlowp/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_gemmlowp_gemmlowp_LICENSE
cp third_party/gloo/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_gloo_LICENSE
cp third_party/googletest/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_LICENSE
cp third_party/googletest/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_LICENSE
cp third_party/googletest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_scripts_generator_LICENSE
cp third_party/googletest/googletest/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_googletest_LICENSE
cp third_party/ideep/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_ideep_LICENSE
cp third_party/ios-cmake/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_ios-cmake_LICENSE
cp third_party/miniz-2.0.8/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_miniz-2.0.8_LICENSE
cp third_party/nccl/nccl/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_nccl_nccl_LICENSE.txt
cp third_party/nccl/nccl/pkg/debian/copyright %{buildroot}/usr/share/package-licenses/pytorch/third_party_nccl_nccl_pkg_debian_copyright
cp third_party/neon2sse/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_neon2sse_LICENSE
cp third_party/onnx-tensorrt/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_onnx-tensorrt_LICENSE
cp third_party/onnx/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_onnx_LICENSE
cp third_party/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_protobuf_LICENSE
cp third_party/psimd/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_psimd_LICENSE
cp third_party/pthreadpool/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_pthreadpool_LICENSE
cp third_party/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_pybind11_LICENSE
cp third_party/python-enum/enum/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_python-enum_enum_LICENSE
cp third_party/python-peachpy/LICENSE.rst %{buildroot}/usr/share/package-licenses/pytorch/third_party_python-peachpy_LICENSE.rst
cp third_party/python-six/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_python-six_LICENSE
cp third_party/sleef/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_sleef_LICENSE.txt
cp third_party/zstd/COPYING %{buildroot}/usr/share/package-licenses/pytorch/third_party_zstd_COPYING
cp third_party/zstd/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_zstd_LICENSE
cp third_party/zstd/contrib/linux-kernel/COPYING %{buildroot}/usr/share/package-licenses/pytorch/third_party_zstd_contrib_linux-kernel_COPYING
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/convert-caffe2-to-onnx
/usr/bin/convert-onnx-to-caffe2

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ATen.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/AccumulateType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Allocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ArrayRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Backend.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Backtrace.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUApplyUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUCharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUDoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUFixedAllocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUGenerator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUHalfType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPULongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUTypeDefault.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDACharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDADoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAGenerator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAHalfType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDALongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CheckGenerator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Config.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Context.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/DLConvertor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Device.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/DeviceGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/DimVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Dispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ExpandUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Formatting.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Generator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Half.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/InferSize.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/InitialTensorOptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Layout.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/LegacyTHDispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/LegacyTHDispatcher.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/MatrixRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/NativeFunctions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Parallel.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/RegisterCPU.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/RegisterCUDA.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Scalar.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ScalarOps.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ScalarType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SmallVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUCharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUDoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPULongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDACharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDADoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDALongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseTensorImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseTensorUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorAccessor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorGeometry.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorOperators.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorOptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Type.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TypeDefault.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TypeExtendedInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/UndefinedType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/WrapDimUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/WrapDimUtilsMulti.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/ATenGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Backtrace.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/DefaultDtype.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Deprecated.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/DimVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Formatting.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Generator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Half.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/LegacyDeviceTypeInit.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/LegacyTypeDispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Range.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Reduction.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Scalar.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/ScalarType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/SparseTensorRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/TensorAccessor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/TensorImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/TensorMethods.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/TensorOptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/Type.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/UndefinedTensorImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/VariableHooksInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/WrapDimMinimal.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/alias_info.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/aten_interned_strings.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/blob.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/context_base.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/function_schema.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/functional.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/interned_strings.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/interned_strings_class.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/ivalue.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/jit_type.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/thread_pool.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/core/typeid.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cpu/FlushDenormal.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cpu/vml.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/ATenCUDAGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/Array.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAConfig.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAContext.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDADevice.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAEvent.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAMultiStreamGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDATypeDefault.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/Exceptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/PinnedMemoryAllocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/_curand_mtgp32_host.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/detail/CUDAGuardImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/detail/CUDAHooks.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/detail/KernelUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Descriptors.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Exceptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Handle.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Handles.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Types.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/cudnn-wrapper.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/CPUGuardImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/CUDAHooksInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/ComplexHooksInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/FunctionTraits.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/HIPHooksInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/ScalarTypeConversions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/div_rtn.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/dlpack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/TH.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THAllocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THBlas.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THDiskFile.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THFile.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THFilePrivate.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateAllTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateCharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateDoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateFloatTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateHalfType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateIntTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateLongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THHalf.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THLapack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THLogAdd.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THMath.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THMemoryFile.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THRandom.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THSize.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THStorageFunctions.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THTensorApply.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THTensorDimApply.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THBlas.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THLapack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THStorageCopy.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorConv.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorLapack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorMath.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorRandom.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/Device.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/DeviceGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/DeviceType.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/Half-inl.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/Half.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/Stream.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/StreamGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/Allocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/Backend.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/Layout.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/Scalar.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/ScalarType.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/ScalarTypeUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/StorageImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/TensorTypeId.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/TensorTypeIdRegistration.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/core/bitcasts.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/cuda/CUDAException.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/cuda/CUDAFunctions.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/cuda/CUDAMacros.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/cuda/CUDAMathCompat.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/cuda/impl/CUDATest.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/impl/DeviceGuardImplInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/impl/FakeGuardImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/impl/InlineDeviceGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/impl/InlineStreamGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/impl/VirtualGuardImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/macros/Export.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/macros/Macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/macros/cmake_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/AlignOf.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Array.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/ArrayRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Backtrace.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/C++17.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Exception.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Flags.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/IdWrapper.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/LeftRight.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Logging.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Metaprogramming.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Optional.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Registry.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/SmallVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/StringUtil.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/Type.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/TypeList.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/TypeTraits.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/UniqueVoidPtr.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/flat_hash_map.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/intrusive_ptr.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/logging_is_google_glog.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/logging_is_not_google_glog.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/string_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/c10/util/typeid.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/THCCachingAllocator_gpu.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/allocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/asan.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/blob.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/blob_serialization.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/blob_serializer_base.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/blob_stats.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/common.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/common_cudnn.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/common_gpu.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/common_omp.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/context.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/context_base.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/context_gpu.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/cudnn_wrappers.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/db.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/event.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/event_cpu.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/flags.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/graph.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/logging.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/memonger.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/module.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net_async_base.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net_async_scheduling.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net_async_tracing.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net_dag_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net_simple.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/net_simple_refcount.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/numa.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/observer.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/operator.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/operator_c10wrapper.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/operator_gradient.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/operator_schema.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/plan_executor.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/prof_dag_counters.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/qtensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/qtensor_serialization.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/scope_guard.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/static_tracepoint.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/static_tracepoint_elfx86.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/stats.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/tensor_impl.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/tensor_int8.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/timer.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/transform.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/types.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/core/workspace.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/caffe2.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/caffe2_legacy.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/caffe2_pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/hsm.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/metanet.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/predictor_consts.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/prof_dag.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/torch.pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/proto/torch_pb.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/bench_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/cast.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/cblas.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/conversions.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/cpu_neon.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/cpuid.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/eigen_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/filler.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/fixed_divisor.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/map_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/math-detail.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/math.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/math_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/murmur_hash3.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/proto_convert.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/proto_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/proto_wrap.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/signal_handler.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/simple_queue.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/smart_tensor_printer.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/string_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/thread_name.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/thread_pool.h
/usr/lib/python3.7/site-packages/torch/lib/include/caffe2/utils/zmq_helper.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/attr.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/buffer_info.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/cast.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/chrono.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/common.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/complex.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/class.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/common.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/descr.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/internals.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/typeid.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/eigen.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/embed.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/eval.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/functional.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/iostream.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/numpy.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/operators.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/options.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/pybind11.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/pytypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/stl.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/stl_bind.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/DataLoader.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Device.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Dtype.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/DynamicTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Exceptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Generator.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Layout.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Module.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/PtrWrapper.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/PythonTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Size.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/StorageDefs.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/THP.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/THP_API.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/THP_export.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/TypeInfo.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Types.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/WindowsTorchApiMacro.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/all.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/arg.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/dataloader_options.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/datasets.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/datasets/base.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/datasets/map.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/datasets/mnist.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/datasets/shared.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/datasets/tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/detail/data_shuttle.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/detail/queue.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/detail/sequencers.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/example.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/iterator.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers/base.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers/custom_batch_request.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers/random.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers/sequential.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers/serialize.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/samplers/stream.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/transforms.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/transforms/base.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/transforms/collate.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/transforms/lambda.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/transforms/stack.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/transforms/tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/data/worker_exception.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/detail/static.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/expanding_array.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/jit.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/cloneable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/module.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/any.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/batchnorm.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/conv.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/dropout.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/embedding.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/functional.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/linear.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/rnn.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/modules/sequential.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/parallel/data_parallel.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/pimpl-inl.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/nn/pimpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/adagrad.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/adam.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/lbfgs.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/optimizer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/rmsprop.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/serialize.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/optim/sgd.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/ordered_dict.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/python.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/serialize.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/serialize/archive.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/serialize/input-archive.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/serialize/output-archive.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/serialize/tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/types.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include/torch/utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/VariableTypeUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/anomaly_mode.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/autograd.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/edge.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/engine.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/function.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/function_hook.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/Functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/VariableType.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/python_functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/python_nn_functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/python_nn_functions_dispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/python_torch_functions_dispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/python_variable_methods_dispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/generated/variable_factories.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/grad_mode.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/input_buffer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/input_metadata.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/profiler.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_anomaly_mode.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_cpp_function.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_engine.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_function.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_hook.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_legacy_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_variable_indexing.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/saved_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/symbolic.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/type_and_shape.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/variable_version.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/byte_order.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/copy_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/Module.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/Stream.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/THCP.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/comm.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/cuda_check.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/device_set.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/nccl.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/override_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/python_comm.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/python_nccl.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/restore_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/serialization.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/undef_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/alias_info.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/assertions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/attributes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/autodiff.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/code_template.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/constants.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/custom_operator.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/dynamic_dag.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/export.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/function_schema.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/generic_if.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/graph_executor.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/graph_node_list.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/hooks_for_testing.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/import.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/import_method.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/interned_strings.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/interned_strings_class.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/interpreter.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/ir.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/ir_views.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/ivalue.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/named_value.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/node_hashing.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/operator.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/alias_analysis.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/batch_mm.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/canonicalize.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/canonicalize_ops.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/common_subexpression_elimination.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/constant_pooling.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/constant_propagation.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/create_autodiff_subgraphs.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/dead_code_elimination.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/erase_number_types.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/graph_fuser.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/inline_autodiff_subgraphs.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/inplace_check.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/loop_unrolling.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/lower_grad_of.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/lower_tuples.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/onnx.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/peephole.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/python_print.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/remove_expands.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/remove_inplace_ops.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/requires_grad_analysis.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/shape_analysis.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/specialize_undef.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/passes/to_batch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/pybind.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/pybind_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/python_arg_flatten.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/python_ir.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/python_tracer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/resource_guard.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/scope.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/builtin_functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/compiler.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/error_report.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/jit_exception.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/lexer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/module.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/parse_string_literal.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/parser.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/python_tree_views.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/tree.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/script/tree_views.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/source_location.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/source_range.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/stack.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/symbolic_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/tracer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/tracing_state.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/type.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/variable_tensor_list.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/python_headers.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/serialization.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/auto_gil.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/cuda_enabled.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/cuda_lazy_init.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/disallow_copy.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/functional.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/hash.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/invalid_arguments.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/memory.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/numpy_stub.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/object_ptr.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/pybind.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_arg_parser.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_compat.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_numbers.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_scalars.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_strings.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_stub.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_tuples.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tempfile.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_apply.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_dtypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_flatten.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_layouts.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_list.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_new.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_numpy.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_types.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tuple_parser.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/variadic.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/variable_tensor_functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/extension.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/script.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytorch/LICENSE
/usr/share/package-licenses/pytorch/NOTICE
/usr/share/package-licenses/pytorch/caffe2_contrib_cuda-convnet2_LICENSE
/usr/share/package-licenses/pytorch/caffe2_mobile_contrib_libopencl-stub_LICENSE
/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_LICENSE
/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_include_half_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_FP16_LICENSE
/usr/share/package-licenses/pytorch/third_party_FXdiv_LICENSE
/usr/share/package-licenses/pytorch/third_party_NNPACK_LICENSE
/usr/share/package-licenses/pytorch/third_party_QNNPACK_LICENSE
/usr/share/package-licenses/pytorch/third_party_QNNPACK_deps_clog_LICENSE
/usr/share/package-licenses/pytorch/third_party_benchmark_LICENSE
/usr/share/package-licenses/pytorch/third_party_cpuinfo_LICENSE
/usr/share/package-licenses/pytorch/third_party_cpuinfo_deps_clog_LICENSE
/usr/share/package-licenses/pytorch/third_party_cub_LICENSE.TXT
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.BSD
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.GPL
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.LGPL
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MINPACK
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MPL2
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.README
/usr/share/package-licenses/pytorch/third_party_eigen_bench_btl_COPYING
/usr/share/package-licenses/pytorch/third_party_fbgemm_LICENSE
/usr/share/package-licenses/pytorch/third_party_gemmlowp_gemmlowp_LICENSE
/usr/share/package-licenses/pytorch/third_party_gloo_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_scripts_generator_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_googletest_LICENSE
/usr/share/package-licenses/pytorch/third_party_ideep_LICENSE
/usr/share/package-licenses/pytorch/third_party_ios-cmake_LICENSE
/usr/share/package-licenses/pytorch/third_party_miniz-2.0.8_LICENSE
/usr/share/package-licenses/pytorch/third_party_nccl_nccl_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_nccl_nccl_pkg_debian_copyright
/usr/share/package-licenses/pytorch/third_party_neon2sse_LICENSE
/usr/share/package-licenses/pytorch/third_party_onnx-tensorrt_LICENSE
/usr/share/package-licenses/pytorch/third_party_onnx_LICENSE
/usr/share/package-licenses/pytorch/third_party_protobuf_LICENSE
/usr/share/package-licenses/pytorch/third_party_psimd_LICENSE
/usr/share/package-licenses/pytorch/third_party_pthreadpool_LICENSE
/usr/share/package-licenses/pytorch/third_party_pybind11_LICENSE
/usr/share/package-licenses/pytorch/third_party_python-enum_enum_LICENSE
/usr/share/package-licenses/pytorch/third_party_python-peachpy_LICENSE.rst
/usr/share/package-licenses/pytorch/third_party_python-six_LICENSE
/usr/share/package-licenses/pytorch/third_party_sleef_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_zstd_COPYING
/usr/share/package-licenses/pytorch/third_party_zstd_LICENSE
/usr/share/package-licenses/pytorch/third_party_zstd_contrib_linux-kernel_COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
