#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytorch
Version  : 0.4.1
Release  : 2
URL      : https://github.com/pytorch/pytorch/archive/v0.4.1.tar.gz
Source0  : https://github.com/pytorch/pytorch/archive/v0.4.1.tar.gz
Source1  : https://github.com/ARM-software/ComputeLibrary/archive/292227986edb37b01061afcad6df18ba9d6ccbeb.tar.gz
Source2  : https://github.com/Maratyszcza/FP16/archive/43d6d17df48ebf622587e7ed9472ea76573799b9.tar.gz
Source3  : https://github.com/Maratyszcza/FXdiv/archive/811b482bcd9e8d98ad80c6c78d5302bb830184b0.tar.gz
Source4  : https://github.com/Maratyszcza/NNPACK/archive/3eb0d453662d05a708f43b108bed9e17b705383e.tar.gz
Source5  : https://github.com/Maratyszcza/PeachPy/archive/07d8fde8ac45d7705129475c0f94ed8925b93473.tar.gz
Source6  : https://github.com/Maratyszcza/cpuinfo/archive/1e6c8c99d27f2b5eb9d2e6231055c6a4115b85e5.tar.gz
Source7  : https://github.com/Maratyszcza/psimd/archive/4ac61b112252778b174575931c641bef661ab3cd.tar.gz
Source8  : https://github.com/Maratyszcza/pthreadpool/archive/2b06b31f6a315162348e1f3c24325eedaf6cc559.tar.gz
Source9  : https://github.com/NVlabs/cub/archive/285aeebaa34b0e8a7670867a2e66c1a52d998d6a.tar.gz
Source10  : https://github.com/NervanaSystems/nervanagpu/archive/d4eefd50fbd7d34a17dddbc829888835d67b5f4a.tar.gz
Source11  : https://github.com/PeachPy/enum34/archive/4cfedc426c4e2fc52e3f5c2b4297e15ed8d6b8c7.tar.gz
Source12  : https://github.com/USCiLab/cereal/archive/51cbda5f30e56c801c07fe3d3aba5d7fb9e6cca4.tar.gz
Source13  : https://github.com/Yangqing/ios-cmake/archive/8abaed637d56f1337d6e1d2c4026e25c1eade724.tar.gz
Source14  : https://github.com/benjaminp/six/archive/15e31431af97e5e64b80af0a3f598d382bcdd49a.tar.gz
Source15  : https://github.com/catchorg/Catch2/archive/0a34cc201ef28bf25c88b0062f331369596cb7b7.tar.gz
Source16  : https://github.com/eigenteam/eigen-git-mirror/archive/e9e95489a0b241412e31f0525e85b2fab386c786.tar.gz
Source17  : https://github.com/facebook/zstd/archive/aec56a52fbab207fc639a1937d1e708a282edca8.tar.gz
Source18  : https://github.com/facebookincubator/gloo/archive/69eef748cc1dfbe0fefed69b34e6545495f67ac5.tar.gz
Source19  : https://github.com/google/benchmark/archive/505be96ab23056580a3a2315abba048f4428b04e.tar.gz
Source20  : https://github.com/google/googletest/archive/69e48e92de43960a316a826293510b7b3deb9eca.tar.gz
Source21  : https://github.com/google/protobuf/archive/2761122b810fe8861004ae785cc3ab39f384d342.tar.gz
Source22  : https://github.com/intel/ideep/archive/4bd9a6800bf7db068187619e0582d34dec9651dc.tar.gz
Source23  : https://github.com/nanopb/nanopb/archive/14efb1a47a496652ab08b1ebcefb0ea24ae4a5e4.tar.gz
Source24  : https://github.com/onnx/onnx-tensorrt/archive/fa0964e8477fc004ee2f49ee77ffce0bf7f711a9.tar.gz
Source25  : https://github.com/onnx/onnx/archive/b2817a682f25f960586f06caa539bbbd7a96b859.tar.gz
Source26  : https://github.com/pybind/pybind11/archive/add56ccdcac23a6c522a2c1174a866e293c61dab.tar.gz
Source27  : https://github.com/shibatch/sleef/archive/6ff7a135a1e31979d1e1844a2e7171dfbd34f54f.tar.gz
Summary  : Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSD-3-Clause-Attribution BSL-1.0 GPL-2.0 GPL-3.0 LGPL-2.1 MIT MPL-2.0 MPL-2.0-no-copyleft-exception Unlicense Zlib
Requires: pytorch-data = %{version}-%{release}
Requires: pytorch-license = %{version}-%{release}
Requires: pytorch-python = %{version}-%{release}
Requires: pytorch-python3 = %{version}-%{release}
Requires: Sphinx
Requires: enum34
Requires: nose
Requires: numpy
Requires: onnx
Requires: opcodes
Requires: pytools
Requires: setuptools
Requires: six
Requires: typing
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : buildreq-meson
BuildRequires : buildreq-scons
BuildRequires : eigen-dev
BuildRequires : enum34
BuildRequires : gflags-dev
BuildRequires : glog-dev
BuildRequires : leveldb
BuildRequires : lmdb-dev
BuildRequires : mkl-dnn-dev
BuildRequires : numactl-dev
BuildRequires : numpy
BuildRequires : onnx
BuildRequires : opcodes
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytools
BuildRequires : setuptools
BuildRequires : six
BuildRequires : snappy-dev
BuildRequires : tox
BuildRequires : virtualenv

%description
========================================
        
        An enumeration is a set of symbolic names (members) bound to unique, constant
        values.  Within an enumeration, the members can be compared by identity, and
        the enumeration itself can be iterated over.
        
            from enum import Enum

%package data
Summary: data components for the pytorch package.
Group: Data

%description data
data components for the pytorch package.


%package dev
Summary: dev components for the pytorch package.
Group: Development
Requires: pytorch-data = %{version}-%{release}
Provides: pytorch-devel = %{version}-%{release}

%description dev
dev components for the pytorch package.


%package license
Summary: license components for the pytorch package.
Group: Default

%description license
license components for the pytorch package.


%package python
Summary: python components for the pytorch package.
Group: Default
Requires: pytorch-python3 = %{version}-%{release}

%description python
python components for the pytorch package.


%package python3
Summary: python3 components for the pytorch package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pytorch package.


%prep
%setup -q -n pytorch-0.4.1
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 1
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 2
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 3
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 4
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 19
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 15
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 12
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 6
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 9
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 16
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 18
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 20
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 22
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 13
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 23
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 10
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 25
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 24
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 21
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 7
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 8
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 26
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 11
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 5
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 14
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 27
cd ..
%setup -q -T -D -n pytorch-0.4.1 -b 17
mkdir -p third_party/ComputeLibrary
mv %{_topdir}/BUILD/ComputeLibrary-292227986edb37b01061afcad6df18ba9d6ccbeb/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/ComputeLibrary
mkdir -p third_party/FP16
mv %{_topdir}/BUILD/FP16-43d6d17df48ebf622587e7ed9472ea76573799b9/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/FP16
mkdir -p third_party/FXdiv
mv %{_topdir}/BUILD/FXdiv-811b482bcd9e8d98ad80c6c78d5302bb830184b0/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/FXdiv
mkdir -p third_party/NNPACK
mv %{_topdir}/BUILD/NNPACK-3eb0d453662d05a708f43b108bed9e17b705383e/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/NNPACK
mkdir -p third_party/benchmark
mv %{_topdir}/BUILD/benchmark-505be96ab23056580a3a2315abba048f4428b04e/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/benchmark
mkdir -p third_party/catch
mv %{_topdir}/BUILD/Catch2-0a34cc201ef28bf25c88b0062f331369596cb7b7/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/catch
mkdir -p third_party/cereal
mv %{_topdir}/BUILD/cereal-51cbda5f30e56c801c07fe3d3aba5d7fb9e6cca4/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/cereal
mkdir -p third_party/cpuinfo
mv %{_topdir}/BUILD/cpuinfo-1e6c8c99d27f2b5eb9d2e6231055c6a4115b85e5/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/cpuinfo
mkdir -p third_party/cub
mv %{_topdir}/BUILD/cub-285aeebaa34b0e8a7670867a2e66c1a52d998d6a/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/cub
mkdir -p third_party/eigen
mv %{_topdir}/BUILD/eigen-git-mirror-e9e95489a0b241412e31f0525e85b2fab386c786/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/eigen
mkdir -p third_party/gloo
mv %{_topdir}/BUILD/gloo-69eef748cc1dfbe0fefed69b34e6545495f67ac5/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/gloo
mkdir -p third_party/googletest
mv %{_topdir}/BUILD/googletest-69e48e92de43960a316a826293510b7b3deb9eca/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/googletest
mkdir -p third_party/ideep
mv %{_topdir}/BUILD/ideep-4bd9a6800bf7db068187619e0582d34dec9651dc/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/ideep
mkdir -p third_party/ios-cmake
mv %{_topdir}/BUILD/ios-cmake-8abaed637d56f1337d6e1d2c4026e25c1eade724/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/ios-cmake
mkdir -p third_party/nanopb
mv %{_topdir}/BUILD/nanopb-14efb1a47a496652ab08b1ebcefb0ea24ae4a5e4/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/nanopb
mkdir -p third_party/nervanagpu
mv %{_topdir}/BUILD/nervanagpu-d4eefd50fbd7d34a17dddbc829888835d67b5f4a/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/nervanagpu
mkdir -p third_party/onnx
mv %{_topdir}/BUILD/onnx-b2817a682f25f960586f06caa539bbbd7a96b859/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/onnx
mkdir -p third_party/onnx-tensorrt
mv %{_topdir}/BUILD/onnx-tensorrt-fa0964e8477fc004ee2f49ee77ffce0bf7f711a9/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/onnx-tensorrt
mkdir -p third_party/protobuf
mv %{_topdir}/BUILD/protobuf-2761122b810fe8861004ae785cc3ab39f384d342/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/protobuf
mkdir -p third_party/psimd
mv %{_topdir}/BUILD/psimd-4ac61b112252778b174575931c641bef661ab3cd/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/psimd
mkdir -p third_party/pthreadpool
mv %{_topdir}/BUILD/pthreadpool-2b06b31f6a315162348e1f3c24325eedaf6cc559/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/pthreadpool
mkdir -p third_party/pybind11
mv %{_topdir}/BUILD/pybind11-add56ccdcac23a6c522a2c1174a866e293c61dab/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/pybind11
mkdir -p third_party/python-enum
mv %{_topdir}/BUILD/enum34-4cfedc426c4e2fc52e3f5c2b4297e15ed8d6b8c7/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/python-enum
mkdir -p third_party/python-peachpy
mv %{_topdir}/BUILD/PeachPy-07d8fde8ac45d7705129475c0f94ed8925b93473/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/python-peachpy
mkdir -p third_party/python-six
mv %{_topdir}/BUILD/six-15e31431af97e5e64b80af0a3f598d382bcdd49a/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/python-six
mkdir -p third_party/sleef
mv %{_topdir}/BUILD/sleef-6ff7a135a1e31979d1e1844a2e7171dfbd34f54f/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/sleef
mkdir -p third_party/zstd
mv %{_topdir}/BUILD/zstd-aec56a52fbab207fc639a1937d1e708a282edca8/* %{_topdir}/BUILD/pytorch-0.4.1/third_party/zstd

%build
## build_prepend content
export NO_CUDA=1
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538521028
python3 setup.py build -b py3

%install
## install_prepend content
export NO_CUDA=1
## install_prepend end
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytorch
cp LICENSE %{buildroot}/usr/share/package-licenses/pytorch/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/pytorch/NOTICE
cp caffe2/contrib/cuda-convnet2/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/caffe2_contrib_cuda-convnet2_LICENSE
cp caffe2/mobile/contrib/libopencl-stub/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/caffe2_mobile_contrib_libopencl-stub_LICENSE
cp third_party/ComputeLibrary/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_LICENSE
cp third_party/ComputeLibrary/include/half/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_include_half_LICENSE.txt
cp third_party/FP16/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_FP16_LICENSE
cp third_party/FXdiv/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_FXdiv_LICENSE
cp third_party/NNPACK/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_NNPACK_LICENSE
cp third_party/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_benchmark_LICENSE
cp third_party/catch/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_catch_LICENSE.txt
cp third_party/cereal/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_cereal_LICENSE
cp third_party/cereal/include/cereal/external/rapidxml/license.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_cereal_include_cereal_external_rapidxml_license.txt
cp third_party/cpuinfo/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_cpuinfo_LICENSE
cp third_party/cub/LICENSE.TXT %{buildroot}/usr/share/package-licenses/pytorch/third_party_cub_LICENSE.TXT
cp third_party/eigen/COPYING.BSD %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.BSD
cp third_party/eigen/COPYING.GPL %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.GPL
cp third_party/eigen/COPYING.LGPL %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.LGPL
cp third_party/eigen/COPYING.MINPACK %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MINPACK
cp third_party/eigen/COPYING.MPL2 %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MPL2
cp third_party/eigen/COPYING.README %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.README
cp third_party/eigen/bench/btl/COPYING %{buildroot}/usr/share/package-licenses/pytorch/third_party_eigen_bench_btl_COPYING
cp third_party/gloo/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_gloo_LICENSE
cp third_party/googletest/googlemock/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_LICENSE
cp third_party/googletest/googlemock/scripts/generator/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_scripts_generator_LICENSE
cp third_party/googletest/googletest/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_googletest_googletest_LICENSE
cp third_party/ideep/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_ideep_LICENSE
cp third_party/ios-cmake/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_ios-cmake_LICENSE
cp third_party/nanopb/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_nanopb_LICENSE.txt
cp third_party/nccl/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_nccl_LICENSE.txt
cp third_party/nccl/debian/copyright %{buildroot}/usr/share/package-licenses/pytorch/third_party_nccl_debian_copyright
cp third_party/nervanagpu/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_nervanagpu_LICENSE
cp third_party/onnx-tensorrt/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_onnx-tensorrt_LICENSE
cp third_party/onnx/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_onnx_LICENSE
cp third_party/protobuf/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_protobuf_LICENSE
cp third_party/psimd/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_psimd_LICENSE
cp third_party/pthreadpool/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_pthreadpool_LICENSE
cp third_party/pybind11/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_pybind11_LICENSE
cp third_party/python-enum/enum/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_python-enum_enum_LICENSE
cp third_party/python-peachpy/LICENSE.rst %{buildroot}/usr/share/package-licenses/pytorch/third_party_python-peachpy_LICENSE.rst
cp third_party/python-six/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_python-six_LICENSE
cp third_party/sleef/LICENSE.txt %{buildroot}/usr/share/package-licenses/pytorch/third_party_sleef_LICENSE.txt
cp third_party/zstd/COPYING %{buildroot}/usr/share/package-licenses/pytorch/third_party_zstd_COPYING
cp third_party/zstd/LICENSE %{buildroot}/usr/share/package-licenses/pytorch/third_party_zstd_LICENSE
cp third_party/zstd/contrib/linux-kernel/COPYING %{buildroot}/usr/share/package-licenses/pytorch/third_party_zstd_contrib_linux-kernel_COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/package-licenses/pytorch/NOTICE
/usr/share/package-licenses/pytorch/third_party_nccl_debian_copyright

%files dev
%defattr(-,root,root,-)
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ATen.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ATenGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/AccumulateType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/AlignOf.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Allocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ArrayRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Backtrace.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUApplyUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUByteStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUByteTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUCharStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUCharTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUCharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUDoubleStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUDoubleTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUDoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUFixedAllocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUFloatStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUFloatTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUGenerator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUHalfStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUHalfTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUHalfType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUIntStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUIntTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPULongStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPULongTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPULongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUShortStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUShortTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CPUShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAByteStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAByteTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDACharStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDACharTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDACharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDADoubleStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDADoubleTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDADoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAFloatStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAFloatTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAGenerator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAHalfStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAHalfTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAHalfType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAIntStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAIntTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDALongStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDALongTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDALongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAShortStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAShortTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CUDAStream.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/CheckGenerator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Config.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Context.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/DLConvertor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Deprecated.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Device.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/DeviceGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/DimVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Dispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Error.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ExpandUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Formatting.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Generator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Half-inl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Half.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Layout.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/MatrixRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/NativeFunctions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/OptionsGuard.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Parallel.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/RegisterCUDA.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Registry.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Retainable.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Scalar.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ScalarType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/ScalarTypeUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SmallVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUCharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUDoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPULongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCPUShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDACharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDADoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDALongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseCUDAShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseTensorImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/SparseTensorRef.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/THLongStorageView.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Tensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorAccessor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorBase.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorGeometry.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorImpl.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorMethods.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorOperators.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorOptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/TensorUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Type.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/UndefinedTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/UndefinedType.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/Utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/WrapDimUtils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/WrapDimUtilsMulti.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/ATenCUDAGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAConfig.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/PinnedMemoryAllocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/detail/CUDAHooks.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Descriptors.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Exceptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Handles.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Types.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/Utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/cudnn/cudnn-wrapper.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/CUDAHooksInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/UniqueVoidPtr.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/detail/VariableHooksInterface.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/dlpack.h
/usr/lib/python3.7/site-packages/torch/lib/include/ATen/optional.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/TH.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THAllocator.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THBlas.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THDiskFile.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THFile.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THFilePrivate.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGeneral.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateAllTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateByteType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateCharType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateDoubleType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateFloatType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateFloatTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateHalfType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateIntType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateIntTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateLongType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THGenerateShortType.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THHalf.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THLapack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THLogAdd.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THMath.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THMemoryFile.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THRandom.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THSize.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THTensorApply.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THTensorDimApply.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/THVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THBlas.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THLapack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THStorage.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THStorageCopy.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensor.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorConv.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorCopy.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorLapack.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorMath.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THTensorRandom.h
/usr/lib/python3.7/site-packages/torch/lib/include/TH/generic/THVector.h
/usr/lib/python3.7/site-packages/torch/lib/include/THNN/Reduction.h
/usr/lib/python3.7/site-packages/torch/lib/include/THNN/THNN.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/attr.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/buffer_info.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/cast.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/chrono.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/common.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/complex.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/class.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/common.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/descr.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/internals.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/detail/typeid.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/eigen.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/embed.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/eval.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/functional.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/iostream.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/numpy.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/operators.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/options.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/pybind11.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/pytypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/stl.h
/usr/lib/python3.7/site-packages/torch/lib/include/pybind11/stl_bind.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/DataLoader.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Device.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Dtype.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/DynamicTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Exceptions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Generator.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Layout.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Module.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/PtrWrapper.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/PythonTypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Size.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/THP.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/THP_API.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/THP_export.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/Types.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/assertions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/anomaly_mode.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/autograd.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/edge.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/engine.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/function.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/function_hook.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/grad_mode.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/input_buffer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/profiler.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_anomaly_mode.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_cpp_function.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_engine.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_function.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_hook.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_legacy_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/python_variable_indexing.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/saved_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/symbolic.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/type_and_shape.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/autograd/variable_version.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/byte_order.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/copy_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/Module.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/Storage.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/Stream.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/THCP.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/comm.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/cuda_check.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/device_set.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/nccl.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/override_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/python_comm.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/python_nccl.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/restore_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/serialization.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/undef_macros.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/cuda/utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/finalizer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/attributes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/autodiff.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/code_template.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/export.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/function_schema.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/fusion_compiler.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/generic_if.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/graph_executor.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/graph_node_list.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/import.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/init.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/interned_strings.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/interpreter.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/ir.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/ivalue.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/named_value.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/operator.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/pybind.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/pybind_utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/python_arg_flatten.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/python_ir.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/python_tracer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/resource_guard.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/source_location.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/stack.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/symbolic_variable.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/tensor_conversions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/tracer.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/tracer_state.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/type.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/variable_flags.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/jit/variable_tensor_list.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/python_headers.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/serialization.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/torch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/auto_gil.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/auto_stream.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/auto_unique_ptr.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/cuda_enabled.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/cuda_lazy_init.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/disallow_copy.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/functional.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/hash.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/invalid_arguments.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/memory.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/numpy_stub.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/object_ptr.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/pybind.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_arg_parser.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_compat.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_numbers.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_scalars.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_strings.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_stub.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/python_tuples.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_apply.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_conversion_dispatch.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_dtypes.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_flatten.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_layouts.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_list.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_new.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_numpy.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tensor_types.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/tuple_parser.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/utils/variadic.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/csrc/variable_tensor_functions.h
/usr/lib/python3.7/site-packages/torch/lib/include/torch/torch.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytorch/LICENSE
/usr/share/package-licenses/pytorch/caffe2_contrib_cuda-convnet2_LICENSE
/usr/share/package-licenses/pytorch/caffe2_mobile_contrib_libopencl-stub_LICENSE
/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_LICENSE
/usr/share/package-licenses/pytorch/third_party_ComputeLibrary_include_half_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_FP16_LICENSE
/usr/share/package-licenses/pytorch/third_party_FXdiv_LICENSE
/usr/share/package-licenses/pytorch/third_party_NNPACK_LICENSE
/usr/share/package-licenses/pytorch/third_party_benchmark_LICENSE
/usr/share/package-licenses/pytorch/third_party_catch_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_cereal_LICENSE
/usr/share/package-licenses/pytorch/third_party_cereal_include_cereal_external_rapidxml_license.txt
/usr/share/package-licenses/pytorch/third_party_cpuinfo_LICENSE
/usr/share/package-licenses/pytorch/third_party_cub_LICENSE.TXT
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.BSD
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.GPL
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.LGPL
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MINPACK
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.MPL2
/usr/share/package-licenses/pytorch/third_party_eigen_COPYING.README
/usr/share/package-licenses/pytorch/third_party_eigen_bench_btl_COPYING
/usr/share/package-licenses/pytorch/third_party_gloo_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_googlemock_scripts_generator_LICENSE
/usr/share/package-licenses/pytorch/third_party_googletest_googletest_LICENSE
/usr/share/package-licenses/pytorch/third_party_ideep_LICENSE
/usr/share/package-licenses/pytorch/third_party_ios-cmake_LICENSE
/usr/share/package-licenses/pytorch/third_party_nanopb_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_nccl_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_nervanagpu_LICENSE
/usr/share/package-licenses/pytorch/third_party_onnx-tensorrt_LICENSE
/usr/share/package-licenses/pytorch/third_party_onnx_LICENSE
/usr/share/package-licenses/pytorch/third_party_protobuf_LICENSE
/usr/share/package-licenses/pytorch/third_party_psimd_LICENSE
/usr/share/package-licenses/pytorch/third_party_pthreadpool_LICENSE
/usr/share/package-licenses/pytorch/third_party_pybind11_LICENSE
/usr/share/package-licenses/pytorch/third_party_python-enum_enum_LICENSE
/usr/share/package-licenses/pytorch/third_party_python-peachpy_LICENSE.rst
/usr/share/package-licenses/pytorch/third_party_python-six_LICENSE
/usr/share/package-licenses/pytorch/third_party_sleef_LICENSE.txt
/usr/share/package-licenses/pytorch/third_party_zstd_COPYING
/usr/share/package-licenses/pytorch/third_party_zstd_LICENSE
/usr/share/package-licenses/pytorch/third_party_zstd_contrib_linux-kernel_COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
